AuthAndAuth/Authorization.Users.Api/Controllers/SiteController.cs
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using IdentityModel.Client;
using Microsoft.AspNetCore.Mvc;

namespace Authorization.Users.Api.Controllers
{
    public class SiteController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public SiteController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> GetOrders()
        {
            // request token
            var authClient = _httpClientFactory.CreateClient();
            var discoveryDocument = await authClient.GetDiscoveryDocumentAsync("https://localhost:5005");
            var tokenResponse = await authClient.RequestClientCredentialsTokenAsync(new ClientCredentialsTokenRequest()
            {
                Address = discoveryDocument.TokenEndpoint,
                ClientId = "client_id",
                ClientSecret = "client_secret",
                Scope = "OrdersAPI"
            });

            // request protected data
            var orderClient = _httpClientFactory.CreateClient();
            orderClient.SetBearerToken(tokenResponse.AccessToken);
            var response = await orderClient.GetAsync("https://localhost:5001/site/getsecrets");
            if (!response.IsSuccessStatusCode)
            {
                ViewBag.Message = response.StatusCode.ToString();
                return View();
            }
            var message = await response.Content.ReadAsStringAsync();

            ViewBag.Message = message;

            return View();
        }
    }
}

AuthAndAuth/Authorization.Users.Api/Views/Shared/_Menu.cshtml
<a asp-controller="Site" asp-action="Index">Index</a>
<a asp-controller="Site" asp-action="GetOrders">Get Orders</a>

AuthAndAuth/Authorization.Users.Api/Views/Site/GetOrders.cshtml
@model object

@{
    Layout = null;
}

@if (!string.IsNullOrEmpty(ViewData["Message"].ToString()))
{
    <p>
        @ViewData["Message"]
    </p>
}

AuthAndAuth/Authorization.Users.Api/Views/Site/Index.cshtml
@{
    ViewBag.Title = "Index";
    //Layout = "_Layout";
}

<h1>Index</h1>

<partial name="_Menu"/>